CREATE TABLE searchDB (
    beerno NUMBER Primary key,
    beerImg VARCHAR(200) Not Null  
);

insert all 
into searchDB(beerno, beerImg) values(55191,'5amsaint.jpg')
into searchDB(beerno, beerImg) values (1432, 'bintang.jpg')
into searchDB(beerno, beerImg) values (23410, 'laoshan.jpg')
into searchDB(beerno, beerImg) values (976, 'singha.jpg')
into searchDB(beerno, beerImg) values (63536, 'adnamsghostship.jpg')
into searchDB(beerno, beerImg) values (1421, 'deliriumnocturnum.jpg')
into searchDB(beerno, beerImg) values (976, 'deliriumargentum.jpg')
into searchDB(beerno, beerImg) values (36594, 'wailuawheat.jpg')
into searchDB(beerno, beerImg) values (6906, 'clausthaleroriginal.jpg')
into searchDB(beerno, beerImg) values (1422, 'bavaria.jpg')
into searchDB(beerno, beerImg) values (45380, 'dammlemon.jpg')
into searchDB(beerno, beerImg) values (4299, 'oettingerHefeweissbier.jpg')
into searchDB(beerno, beerImg) values (4291, 'oettingerAlkoholfrei.jpg')
into searchDB(beerno, beerImg) values (229743, 'hiteZero.jpg')
into searchDB(beerno, beerImg) values (242043, 'hanaleIislandIpa.jpg')
into searchDB(beerno, beerImg) values (132406, 'kingGoseAle.jpg')
into searchDB(beerno, beerImg) values (2637, 'weisseOriginal.jpg')
into searchDB(beerno, beerImg) values (41091, 'schofferhoferhefeweizengrapefruit.jpg')
into searchDB(beerno, beerImg) values (27137, 'macaubeer.jpg')
into searchDB(beerno, beerImg) values (52126, 'volfasengelmanrinktinis.jpg')
into searchDB(beerNo, beerImg) values (50578, 'litovalmoravan.jpg')
into searchDB(beerNo, beerImg) values (1641, 'premiumbeer.jpg')
into searchDB(beerNo, beerImg) values (83075, 'zahringerhefeweizen.jpg')
into searchDB(beerNo, beerImg) values (935, 'warsteiner.jpg')
into searchDB(beerNo, beerImg) values (1317, 'staropramenlager.jpg')
into searchDB(beerNo, beerImg) values (115552, 'grevensteineroriginal.jpg')
into searchDB(beerNo, beerImg) values (52539, 'yanjingbeer.jpg')
into searchDB(beerNo, beerImg) values (62476, '5,0originalexport.jpg')
into searchDB(beerNo, beerImg) values (24720, 'bluelabelale.jpg')
into searchDB(beerNo, beerImg) values (280, 'lowenbrau.jpg')
into searchDB(beerNo, beerImg) values (16767, 'balihai.jpg')
into searchDB(beerNo, beerImg) values (5798, 'louiskriek.jpg')
into searchDB(beerNo, beerImg) values (26244, 'louispeche.jpg')
into searchDB(beerNo, beerImg) values (160082, 'louisfond.jpg')
into searchDB(beerNo, beerImg) values (7451, 'lagoudale.jpg')
into searchDB(beerNo, beerImg) values (134703, 'degoudalegrandcru.jpg')
into searchDB(beerNo, beerImg) values (13159, 'oudegeuzeboon.jpg')
into searchDB(beerNo, beerImg) values (129878, 'paljasblond.jpg')
into searchDB(beerNo, beerImg) values (1716, 'aveclesbonsvoeux.jpg')
into searchDB(beerNo, beerImg) values (12738, 'VanDiestFruliStrawberryBeer.jpg')
into searchDB(beerNo, beerImg) values (197183, 'citradelictangerineipa.jpg')
into searchDB(beerNo, beerImg) values (275731, 'fattirebelgianwhite.jpg')
into searchDB(beerNo, beerImg) values (751, 'sweetwater420extrapaleale.jpg')
into searchDB(beerNo, beerImg) values (600, 'lindemanskriek.jpg')
into searchDB(beerNo, beerImg) values (601, 'lindemanscassis.jpg')
into searchDB(beerNo, beerImg) values (6104, 'lindemansgueuzecuveerene.jpg')
into searchDB(beerNo, beerImg) values (10482, 'monkscafeflemishsourale.jpg')
into searchDB(beerNo, beerImg) values (100185, 'cuveemamzelle.jpg')
into searchDB(beerNo, beerImg) values (457725, 'coopersvintageale.jpg')
into searchDB(beerNo, beerImg) values (251571, 'sierranevadapaleale.jpg')
into searchDB(beerNo, beerImg) values (70471, 'chaoticdoubleipa.jpg')
into searchDB(beerNo, beerImg) values (20134, 'martenspilsener.jpg')
into searchDB(beerNo, beerImg) values (13889, 'tripelvandegarre.jpg')
into searchDB(beerNo, beerImg) values (1229, 'kapuzinerweissbier.jpg')
into searchDB(beerNo, beerImg) values (388, 'paulaner.jpg')
into searchDB(beerNo, beerImg) values (453324, 'heverleewitte.jpg')
into searchDB(beerNo, beerImg) values (362972, 'reeperbexotischesipa.jpg')
into searchDB(beerNo, beerImg) values (362983, 'reeperbblondesweissbier.jpg')
into searchDB(beerNo, beerImg) values (36871, 'redrock.jpg')
into searchDB(beerNo, beerImg) values (28593, 'kaiserdompilsener.jpg')
into searchDB(beerNo, beerImg) values (55207, 'kaiserdomhefeweissbiernaturtrub.jpg')
into searchDB(beerNo, beerImg) values (90181, 'kaiserdomkellerbierunfiltriert.jpg')
into searchDB(beerNo, beerImg) values (8045, 'achelbruintrappist.jpg')
into searchDB(beerNo, beerImg) values (2508, 'maredsousbrune.jpg')
into searchDB(beerNo, beerImg) values (175025, 'baristachocolatequad.jpg')
into searchDB(beerNo, beerImg) values (131290, 'kaguablanc.jpg')
into searchDB(beerNo, beerImg) values (131291, 'kaguarouge.jpg')
into searchDB(beerNo, beerImg) values (79680, 'willianbrauweizen.jpg')
into searchDB(beerNo, beerImg) values (1944, 'spatenmunchnerhell.jpg')
into searchDB(beerNo, beerImg) values (334028, 'fearmovieloins.jpg')
into searchDB(beerNo, beerImg) values (216036, 'arkbehighipa.jpg')
into searchDB(beerNo, beerImg) values (255668, 'hugme.jpg')
into searchDB(beerNo, beerImg) values (326018, 'dongbinggo.jpg')
into searchDB(beerNo, beerImg) values (258014, 'blackswan.jpg')
into searchDB(beerNo, beerImg) values (500001, 'gangseomildale.jpg')
into searchDB(beerNo, beerImg) values (500002, 'hanriver.jpg')
into searchDB(beerNo, beerImg) values (500003, 'seoul.jpg')
into searchDB(beerNo, beerImg) values (500004, 'jeolla.jpg')
into searchDB(beerNo, beerImg) values (500005, 'seocho.jpg')
into searchDB(beerNo, beerImg) values (500006, 'standardale.jpg')
into searchDB(beerNo, beerImg) values (500007, 'pellongale.jpg')
into searchDB(beerNo, beerImg) values (500008, 'slice.jpg')
into searchDB(beerNo, beerImg) values (500009, 'sunset.jpg')
into searchDB(beerNo, beerImg) values (500010, 'night.jpg')
into searchDB(beerNo, beerImg) values (500011, 'HeungBeer.jpg')
into searchDB(beerNo, beerImg) values (500012, 'ChimliAle.jpg')
into searchDB(beerNo, beerImg) values (500013, 'Keumgangsan.jpg')
into searchDB(beerNo, beerImg) values (500014, 'Beakdusan.jpg')
into searchDB(beerNo, beerImg) values (500015, 'Hallasan.jpg')
into searchDB(beerNo, beerImg) values (500016, 'fitz.jpg')
into searchDB(beerNo, beerImg) values (500017, 'terra.jpg')
into searchDB(beerNo, beerImg) values (500018, 'max.jpg')
into searchDB(beerNo, beerImg) values (500019, 'stout.jpg')
into searchDB(beerno, beerImg) values(403,'acmeipa.jpg')
into searchDB(beerno, beerImg) values(406,'acmepaleale.jpg')
into searchDB(beerno, beerImg) values(2779,'asahi.jpg')
into searchDB(beerno, beerImg) values(709,'ballastpointbigeye.jpg')
into searchDB(beerno, beerImg) values(29619,'ballastpointsculpin.jpg')
into searchDB(beerno, beerImg) values(5701,'ballastpointwahoo.jpg')
into searchDB(beerno, beerImg) values(2435,'beck.jpg')
into searchDB(beerno, beerImg) values(55287,'benediktiner.jpg')
into searchDB(beerno, beerImg) values(22592,'bigwave.jpg')
into searchDB(beerno, beerImg) values(50423,'blacksheep.jpg')
into searchDB(beerno, beerImg) values(25625,'blanc.jpg')
into searchDB(beerno, beerImg) values(1212,'bluemoon.jpg')
into searchDB(beerno, beerImg) values(65,'budweiser.jpg')
into searchDB(beerno, beerImg) values(10784,'calderaipa.jpg')
into searchDB(beerno, beerImg) values(2270,'carlsberg.jpg')
into searchDB(beerno, beerImg) values(8750,'cass.jpg')
into searchDB(beerno, beerImg) values(7609,'chang.jpg')
into searchDB(beerno, beerImg) values(2512,'chimayblue.jpg')
into searchDB(beerno, beerImg) values(7364,'cisk.jpg')
into searchDB(beerno, beerImg) values(49787,'coedoruri.jpg')
into searchDB(beerno, beerImg) values(232,'corona.jpg')
into searchDB(beerno, beerImg) values(15804,'desperados.jpg')
into searchDB(beerno, beerImg) values(695,'duvel.jpg')
into searchDB(beerno, beerImg) values(222579,'elvisjuice.jpg')
into searchDB(beerno, beerImg) values(2434,'erdinger.jpg')
into searchDB(beerno, beerImg) values(14687,'estrelladamn.jpg')
into searchDB(beerno, beerImg) values(5753,'firerock.jpg')
into searchDB(beerno, beerImg) values(1946,'franziskaner.jpg')
into searchDB(beerno, beerImg) values(7813,'gingakogen.jpg')
into searchDB(beerno, beerImg) values(3968,'goose.jpg')
into searchDB(beerno, beerImg) values(246,'heineken.jpg')
into searchDB(beerno, beerImg) values(1167,'heinekendark.jpg')
into searchDB(beerno, beerImg) values(16429,'hitachinoclassicale.jpg')
into searchDB(beerno, beerImg) values(2013,'hitachinonestwhiteale.jpg')
into searchDB(beerno, beerImg) values(89036,'hite.jpg')
into searchDB(beerno, beerImg) values(248,'hoegaarden.jpg')
into searchDB(beerno, beerImg) values(832,'honeyBrown.jpg')
into searchDB(beerno, beerImg) values(160538,'hophouse13.jpg')
into searchDB(beerno, beerImg) values(8131,'huberweisses.jpg')
into searchDB(beerno, beerImg) values(1670,'indica.jpg')
into searchDB(beerno, beerImg) values(52429,'inedit.jpg')
into searchDB(beerno, beerImg) values(89096,'jackhammer.jpg')
into searchDB(beerno, beerImg) values(426877,'jejuwitale.jpg')
into searchDB(beerno, beerImg) values(52083,'kilkenny.jpg')
into searchDB(beerno, beerImg) values(266,'kingfisher.jpg')
into searchDB(beerno, beerImg) values(807,'kirin.jpg')
into searchDB(beerno, beerImg) values(120494,'kloud.jpg')
into searchDB(beerno, beerImg) values(16273,'kozel.jpg')
into searchDB(beerno, beerImg) values(1499,'kukmin.jpg')
into searchDB(beerno, beerImg) values(1836,'lachouffe.jpg')
into searchDB(beerno, beerImg) values(1862,'leffebrown.jpg')
into searchDB(beerno, beerImg) values(221,'londonPorter.jpg')
into searchDB(beerno, beerImg) values(5328,'longboard.jpg')
into searchDB(beerno, beerImg) values(365571,'subwaymosaicipa.jpg')
into searchDB(beerno, beerImg) values(2280,'miller.jpg')
into searchDB(beerno, beerImg) values(412,'oldrasputin.jpg')
into searchDB(beerno, beerImg) values(1256,'paulaner.jpg')
into searchDB(beerno, beerImg) values(97563,'peanutbuttermilkstout.jpg')
into searchDB(beerno, beerImg) values(429,'pilsner.jpg')
into searchDB(beerno, beerImg) values(39435,'punkipa.jpg')
into searchDB(beerno, beerImg) values(410,'redsealale.jpg')
into searchDB(beerno, beerImg) values(102,'samuel.jpg')
into searchDB(beerno, beerImg) values(5366,'sanmiguel.jpg')
into searchDB(beerno, beerImg) values(8128,'suntory.jpg')
into searchDB(beerno, beerImg) values(10071,'sapporo.jpg')
into searchDB(beerno, beerImg) values(276,'sierranevada_paleale.jpg')
into searchDB(beerno, beerImg) values(449,'stella.jpg')
into searchDB(beerno, beerImg) values(88,'stone_ipa.jpg')
into searchDB(beerno, beerImg) values(275425,'taedonggang.jpg')
into searchDB(beerno, beerImg) values(31931,'tangerine.jpg')
into searchDB(beerno, beerImg) values(2176,'tiger.jpg')
into searchDB(beerno, beerImg) values(767,'tsingtao.jpg')
into searchDB(beerno, beerImg) values(17141,'urbanwheatale.jpg')
into searchDB(beerno, beerImg) values(1541,'victoriabitter.jpg')
into searchDB(beerno, beerImg) values(1530,'xxxx.jpg')
into searchDB(beerno, beerImg) values(800,'yebisu.jpg')
into searchDB(beerno, beerImg) values(2762,'OB.jpg')
into searchDB(beerno, beerImg) values(175423,'hoegaardenRose.jpg')
into searchDB(beerno, beerImg) values(190730,'mochastout.jpg')
into searchDB(beerno, beerImg) values(7511,'okinawa.jpg')
into searchDB(beerno, beerImg) values(8759,'beerlao.jpg')
into searchDB(beerno, beerImg) values(92928,'llager.jpg')
into searchDB(beerno, beerImg) values(92893,'lweizen.jpg')
into searchDB(beerno, beerImg) values(114541,'ldark.jpg')
SELECT * FROM dual;